version: 1.0.{build}
os: Visual Studio 2015
skip_tags: true
configuration: Release

install:
    - cmd: git submodule update --init --recursive

assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: '{version}'
  assembly_file_version: '{version}'

before_build:
  - ps: .\scripts\set-version.ps1
  - cmd: dotnet --info
  - cmd: dotnet restore --verbosity n

build_script:
  - cmd: dotnet build -c Release

test_script:
  - cmd: dotnet test -c release WebOptimizationProject.Tests\WebOptimizationProject.Tests.csproj

after_test:
  - cmd: dotnet pack -c Release WebOptimizationProject\

artifacts:
- path: 'WebOptimizationProject\bin\Release\*.nupkg'
  name: nugetPackages

deploy:
- provider: GitHub
  auth_token:
    secure: do7S++r1rE5E3IZujCoMONsWYJNF7eoRoPyJbxSD851I850OlEq0gsHH/Tji7o00
  artifact: nugetPackages,droppackage
- provider: NuGet
  api_key:
    secure: pVOzQthQbu7P9SUQwjG43ZEMcwAp7dVbe4BkDVEwJFu1gWK+L11L9mdfGLC5iO5Z
  skip_symbols: true
  artifact: /.*\.nupkg/